-- LinkJac / JAC OS decommission -- unschedule all 156 JAC +
-- Co-Trader pg_cron jobs so they stop firing and stop generating charges.
--
-- Duck Countdown is NOT touched: the explicit name array contains zero
-- hunt- jobs, and the in-loop guard RAISEs (aborting the whole migration)
-- if any name matches hunt%. One misclassified job cannot slip through.
--
-- Mechanism: cron.unschedule(jobname) -- pg_cron's own API, the same call
-- every cron migration in this repo uses. Direct cron.job DML is permission
-- denied (42501), so unschedule is the working path.
--
-- REVERSIBLE: every job's schedule + command lives in this repo's
-- migrations; re-running the relevant cron.schedule() calls restores any
-- job. No data dropped, no table dropped, no edge function deleted.
SET search_path = public, extensions;

DO $decom$
DECLARE
  j text;
  removed int := 0;
BEGIN
  FOREACH j IN ARRAY ARRAY[
    'backfill-embeddings-every-30min',
    'brain-insights-cleanup',
    'brain-insights-evening',
    'brain-insights-morning',
    'ct-alert-book-commit',
    'ct-alert-post-mortem',
    'ct-analyst-ingester',
    'ct-attribute-signals-nightly',
    'ct-brief-reflection-rth',
    'ct-butterfly-detector-rth',
    'ct-butterfly-grader-intraday',
    'ct-butterfly-grader-nextclose',
    'ct-central-bank-ingester',
    'ct-contract-poller',
    'ct-contract-poller-offhours',
    'ct-correlation-compute',
    'ct-correlations-ingester',
    'ct-cron-health-check',
    'ct-curiosity',
    'ct-d3-feature-extension',
    'ct-daily-brief',
    'ct-debate-outcome-scorer',
    'ct-detector-flow-stack-v1',
    'ct-detector-pair-qqq-iwm-rth',
    'ct-detector-scoreboard-update-offhours',
    'ct-detector-scoreboard-update-rth',
    'ct-detector-scoreboard-update-weekend',
    'ct-detector-scorer-rth',
    'ct-detector-small-cap-inverted-put-rth',
    'ct-detector-smart-money-repeat-rth',
    'ct-detector-unusual-oi-rth',
    'ct-detector-weekly-atm-voi-rth',
    'ct-detector-whale-off',
    'ct-detector-whale-rth',
    'ct-detector-zerodte-opening-call-rth',
    'ct-detector-zerodte-put-voi-rth',
    'ct-disagreement-materializer',
    'ct-drawdown-watch',
    'ct-earnings-moves-sync',
    'ct-earnings-pre-event-check',
    'ct-earnings-sync',
    'ct-edge-miner',
    'ct-embed-breaking-news-24x7',
    'ct-embed-specialist-reads-rth',
    'ct-embed-tape-commentary-rth',
    'ct-eod-positioning',
    'ct-eod-report',
    'ct-eod-report-catchup',
    'ct-eod-specialist-narrative',
    'ct-eod-summary',
    'ct-event-calendar-ingester',
    'ct-flag-analysis-corpus-refresh-nightly',
    'ct-flag-grader',
    'ct-flow-ingester-marketwide',
    'ct-flow-ingester-perticker-offrth',
    'ct-flow-ingester-perticker-rth',
    'ct-flow-pulse-capture',
    'ct-fundamentals-sync',
    'ct-grader',
    'ct-heatmap-snapshot-eod',
    'ct-heatmap-snapshot-offrth',
    'ct-heatmap-snapshot-rth',
    'ct-historical-quote-backfill',
    'ct-hypothesis-health-check',
    'ct-hypothesis-proposer',
    'ct-hypothesis-reaper',
    'ct-indicator-events-ingester',
    'ct-insider-ingester',
    'ct-institutional-ingester',
    'ct-interval-flow-ingester',
    'ct-iv-shift-watch',
    'ct-lean-score-close',
    'ct-lean-score-live',
    'ct-lessons-curator',
    'ct-mcp-verification-runner',
    'ct-news-causality',
    'ct-news-ingester-weekday',
    'ct-news-ingester-weekend',
    'ct-news-sweep-rth',
    'ct-oi-overnight-summary',
    'ct-oi-snapshot-close',
    'ct-oi-snapshot-mid',
    'ct-oi-snapshot-open',
    'ct-options-screener-ingester',
    'ct-playbook-curator',
    'ct-political-ingester',
    'ct-prediction-markets-ingester',
    'ct-prediction-smart-money-ingester',
    'ct-premarket-scan',
    'ct-price-backfill-weekly',
    'ct-price-live-poll',
    'ct-price-tick-capture',
    'ct-price-ticks-retention',
    'ct-print-grader-offhours',
    'ct-print-grader-rth',
    'ct-pulse-tick',
    'ct-reflect-to-jac',
    'ct-regime-capture-offhours',
    'ct-regime-capture-rth',
    'ct-regime-watch',
    'ct-score-flow-continuous',
    'ct-score-self-grade-nightly',
    'ct-seasonality-ingester',
    'ct-sector-tide-ingester',
    'ct-self-grader',
    'ct-session-analog',
    'ct-short-interest-ingester',
    'ct-signature-watcher-offhours',
    'ct-signature-watcher-rth',
    'ct-skew-ingester',
    'ct-slack-digest',
    'ct-slack-push-flag',
    'ct-specialist-aapl',
    'ct-specialist-amzn',
    'ct-specialist-dispatcher',
    'ct-specialist-googl',
    'ct-specialist-iwm',
    'ct-specialist-meta',
    'ct-specialist-msft',
    'ct-specialist-nvda',
    'ct-specialist-qqq',
    'ct-specialist-score-v2-nightly',
    'ct-specialist-scoreboard-nightly',
    'ct-specialist-spy',
    'ct-specialist-tsla',
    'ct-spy-capture',
    'ct-sweep-cluster',
    'ct-system-warden',
    'ct-tape-reader-rth',
    'ct-tavily-news-watcher-weekday',
    'ct-tavily-news-watcher-weekend',
    'ct-technicals-ingester',
    'ct-ticker-baselines-nightly',
    'ct-ticker-snapshot-builder',
    'ct-trade-advisories',
    'ct-trade-idea-generator',
    'ct-uw-endpoint-health-check',
    'ct-uw-mcp-scout',
    'ct-uw-spot-poll',
    'ct-vix-capture-eod',
    'ct-vix-capture-rth',
    'ct-watcher',
    'ct-yield-curve-ingester',
    'ct_contract_poller_log_rotate',
    'distill-principles',
    'jac-emission-detector',
    'jac-heartbeat',
    'jac-morning-brief',
    'jac-watch-scheduler',
    'market-snapshot',
    'memory-decay-sweep',
    'reminder-evening',
    'reminder-morning',
    'reminder-timed',
    'stale-task-cleanup',
    'sync-all-codebases'
  ]
  LOOP
    IF j LIKE 'hunt-%' OR j LIKE 'hunt\_%' ESCAPE '\' THEN
      RAISE EXCEPTION 'DUCK COUNTDOWN GUARD: refusing to unschedule %', j;
    END IF;
    IF EXISTS (SELECT 1 FROM cron.job WHERE jobname = j) THEN
      PERFORM cron.unschedule(j);
      removed := removed + 1;
    END IF;
  END LOOP;
  RAISE NOTICE 'JAC decommission: % JAC/Co-Trader cron jobs unscheduled', removed;
END
$decom$;
