-- =============================================================================
-- 20260502030000_ct_eod_specialist_narratives.sql
--
-- ct-eod-specialist-narrative consumer storage. One row per
-- (session_date, ticker). Pattern mirror of ct_eod_reports — Sonnet
-- writes a 2-3 paragraph narrative per ticker covering the day's
-- specialist activity (reads, flags, grades, regime context).
--
-- Read-only consumer — does NOT modify specialist context. C1
-- measurement-window-safe.
-- =============================================================================
SET search_path = public, extensions;

CREATE TABLE IF NOT EXISTS public.ct_eod_specialist_narratives (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  session_date        date NOT NULL,
  ticker              text NOT NULL,
  narrative           text NOT NULL,
  reads_count         integer NOT NULL DEFAULT 0,
  flags_count         integer NOT NULL DEFAULT 0,
  grades_count        integer NOT NULL DEFAULT 0,
  composite_hit_rate  numeric,            -- (wins + 0.5*partials)/n_graded if any grades landed
  closing_lean        text,                -- last specialist read's direction_lean
  closing_conviction  integer,             -- last specialist read's conviction
  generated_at        timestamptz NOT NULL DEFAULT now(),
  generated_by_model  text,
  cost_usd            numeric,
  tokens_in           integer,
  tokens_out          integer,
  validator_warnings  jsonb,
  brain_organs_used   text[],
  triggered_by        text DEFAULT 'scheduled',
  UNIQUE (session_date, ticker)
);

CREATE INDEX IF NOT EXISTS ct_eod_spec_narr_session
  ON public.ct_eod_specialist_narratives (session_date DESC, ticker);
CREATE INDEX IF NOT EXISTS ct_eod_spec_narr_ticker
  ON public.ct_eod_specialist_narratives (ticker, session_date DESC);

ALTER TABLE public.ct_eod_specialist_narratives ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS ct_eod_spec_narr_read ON public.ct_eod_specialist_narratives;
CREATE POLICY ct_eod_spec_narr_read ON public.ct_eod_specialist_narratives
  FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS ct_eod_spec_narr_svc ON public.ct_eod_specialist_narratives;
CREATE POLICY ct_eod_spec_narr_svc ON public.ct_eod_specialist_narratives
  FOR ALL TO service_role USING (true) WITH CHECK (true);

COMMENT ON TABLE public.ct_eod_specialist_narratives IS
  'Daily per-ticker narrative summarizing specialist activity, flags, grades, regime context. One row per (session_date, ticker). Generated by ct-eod-specialist-narrative cron at 4:30 PM ET.';
